name: Smoke test
on:
  pull_request:
  push:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Lint
        run: helm lint .
      - name: Template default
        run: helm template test .
      - name: Install CRD chart
        run: helm install crds oci://ghcr.io/vshn/rabbitmq-crd-chart/rabbitmq-crd --version 0.0.1 --wait --timeout 5m
      - name: Install chart
        run: helm install test . --wait --timeout 10m --create-namespace --namespace rabbitmq-system
      - name: Wait for operators
        run: |
          kubectl wait --for=condition=available deployment/rabbitmq-cluster-operator -n rabbitmq-system --timeout=600s
      - name: Test all test-value-files
        run: |
          failed=false
          for i in test/test-value-files/*.yaml; do
            set +e
            helm upgrade test . --wait --timeout 10m --create-namespace --namespace rabbitmq-system -f $i
            if [ $? -ne 0 ]; then
              failed=true
            fi
            kubectl wait --for=condition=available deployment/rabbitmq-cluster-operator -n rabbitmq-system --timeout=600s
            set -e
            if [ $? -ne 0 ]; then
              failed=true
            fi
          done
          if [ "$failed" = true ]; then
            exit 1
          fi
      - name: Uninstall chart
        run: helm uninstall test -n rabbitmq-system --wait
      - name: Assert CRDs retained
        run: |
          kubectl get crd rabbitmqclusters.rabbitmq.com
